In [1]:
import glob
from ase.io import read,write
from ase import Atoms,Atom
from collections import Counter
import numpy as np
from tqdm import tqdm
from make_representation import *
import pickle

In [2]:
cif_path = './cif'
#glob 모듈의 glob 함수는 사용자가 제시한 조건에 맞는 파일명을 리스트 형식으로 반환한다.
cif_list = glob.glob(cif_path+'/*.cif')

results = []
name_list = [] 

for i in cif_list:
    name = i.split(',')[0]
    atoms =read(i)
    s = atoms.get_chemical_symbols()
    n_fe = s.count('Fe')
    n_o = s.count('O')
    print(n_fe, n_o)
    print(atoms)
    if n_fe > 40 or n_o > 40:
        continue
    else:
        image = do_feature(atoms)
        print(image)

        results.append(image)
        name_list.append(name)


results = np.array(results)
# print(results)

print(results.shape)
np.save('unique_FeO',results)
#name_list는 파일명이다.
with open("unique_FeO_name_list",'wb') as f:
    pickle.dump(name_list,f)

17 18
Atoms(symbols='Fe17O18', pbc=True, cell=[[6.834295, 0.0, 0.0], [-3.359349001847445, 7.460252004385914, 0.0], [-0.6491059996068315, -3.5174609987323757, 7.412993996123034]], spacegroup_kinds=...)
[[0.22780983 0.27272409 0.27436057]
 [0.61629848 0.52512893 0.6346779 ]
 [0.61392867 0.31726133 0.53687067]
 [0.72856533 0.34762933 0.79796933]
 [0.616842   0.54171067 0.76249267]
 [0.48849733 0.27402067 0.275912  ]
 [0.72164333 0.57150667 0.355158  ]
 [0.383158   0.45828933 0.23750733]
 [0.27814533 0.20234867 0.42236067]
 [0.5        0.5        0.5       ]
 [0.83190667 0.38263867 0.38444   ]
 [0.72185467 0.79765133 0.57763933]
 [0.38607133 0.68273867 0.46312933]
 [0.27835667 0.42849333 0.644842  ]
 [0.51150267 0.72597933 0.724088  ]
 [0.16809333 0.61736133 0.61556   ]
 [0.27143467 0.65237067 0.20203067]
 [0.383754   0.23684067 0.68802267]
 [0.616246   0.76315933 0.31197733]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.   

c:\Users\Sejong\anaconda3\envs\yj\lib\site-packages\ase\utils\__init__.py:62: FutureWarning: Please use atoms.cell.cellpar() instead
  warnings.warn(warning)


32 48
Atoms(symbols='Fe32O48', pbc=True, cell=[[10.03799652, 0.0, 0.0], [1.1829343242796266, 10.261644366396515, 0.0], [0.793742833695215, 0.9134249649661734, 10.264096751588344]], spacegroup_kinds=...)
32 48
Atoms(symbols='Fe32O48', pbc=True, cell=[[10.2329503, 0.0, 0.0], [0.47681274751537595, 10.255194268128596, 0.0], [0.08077834430735951, 0.5632571791000012, 10.37217848337225]], spacegroup_kinds=...)
12 18
Atoms(symbols='Fe12O18', pbc=True, cell=[[5.3875279, 0.0, 0.0], [-2.693763949999999, 4.66573602499743, 0.0], [0.0, 0.0, 14.810113]], spacegroup_kinds=...)
[[0.17958426 0.17958426 0.49367043]
 [0.5        0.5        0.66666667]
 [0.18353133 0.59845133 0.322362  ]
 [0.58158667 0.81646867 0.322362  ]
 [0.40154867 0.41841333 0.322362  ]
 [0.424962   0.83333067 0.653714  ]
 [0.57503533 0.575038   0.653714  ]
 [0.16666933 0.42496467 0.653714  ]
 [0.16666667 0.16666667 0.77587267]
 [0.16666667 0.16666667 0.21955933]
 [0.16666667 0.16666667 0.55612667]
 [0.38888889 0.61111111 0.79315067]
