In [1]:
import os
import glob
import numpy as np
from ase.io import read, write
from ase import Atoms,Atom
import view_atoms_gan
import itertools
import make_representation
from tqdm import tqdm
import pickle

In [2]:
def do_supercell(image, n = None):
    atoms, image = view_atoms_gan.view_atoms(image, view = False)
    # s  = atoms.get_chemical_symbols()
    # n_mg = s.count("Mg")
    # n_mn = s.count('Mn')
    # n_o = s.count('O')

    atoms_x = atoms.repeat((2,1,1))
    atoms_y = atoms.repeat((1,2,1))
    atoms_z = atoms.repeat((1,1,2))
    
    image_x = make_representation.do_feature(atoms_x).reshape(1,82,3)
    image_y = make_representation.do_feature(atoms_y).reshape(1,82,3)
    image_z = make_representation.do_feature(atoms_z).reshape(1,82,3)
    
    new_images = np.vstack((image_x,image_y,image_z))
    return new_images

In [3]:
if __name__ == "__main__":
    images = np.load('unique_FeO_comp_dict',allow_pickle=True)
    with open("unique_FeO_name_list" ,'rb') as f:
        name_list = pickle.load(f)
    result_comp_dict = {}
    k = images.keys()
    new_name_list = []
    count = 0
    s = 0
    for comp in tqdm(k):
        temp = comp.split('_')
        n_fe = int(temp[0])
        n_o = int(temp[1])
        #cell 안에 있는 원자의 갯수가 다음 조건을 만족할 때 supercell을 만듬
        if n_fe <= 20 and n_o <= 20:
            print(comp)
            image_and_name_list = images[comp]
            print(len(image_and_name_list))
            s += len(image_and_name_list)
            for ii in range(len(image_and_name_list)):
                name = image_and_name_list[ii][1]
                image = image_and_name_list[ii][0]
                t = do_supercell(image)
                print(t)
                if count == 0 and ii == 0:
                    supercell_data = t
                    new_name_list = [name,name,name]
                else:
                    supercell_data = np.vstack((supercell_data,t))
                    new_name_list += [name,name,name]
                print(supercell_data.shape)
                print(len(new_name_list))
            count += 1
        else:
            pass

    print("supercell data shape is ",supercell_data.shape)
    print("new name data length is ",len(new_name_list))
    print(count)
    np.save("supercell_only",supercell_data)               
    with open("supercell_only_name_list", 'wb') as f:
        pickle.dump(new_name_list, f)

  0%|          | 0/52 [00:00<?, ?it/s]c:\Users\Sejong\anaconda3\envs\yj\lib\site-packages\ase\utils\__init__.py:62: FutureWarning: Please use atoms.cell.cellpar() instead
  warnings.warn(warning)
 96%|█████████▌| 50/52 [00:00<00:00, 247.99it/s]

17_18
1
[[[0.45561967 0.27272409 0.27436057]
  [0.61629848 0.52512893 0.6346779 ]
  [0.39029767 0.31726133 0.53687067]
  [0.447616   0.34762933 0.79796933]
  [0.39175433 0.54171067 0.76249267]
  [0.327582   0.27402067 0.275912  ]
  [0.444155   0.57150667 0.355158  ]
  [0.27491233 0.45828933 0.23750733]
  [0.222406   0.20234867 0.42236067]
  [0.33333333 0.5        0.5       ]
  [0.49928667 0.38263867 0.38444   ]
  [0.44426067 0.79765133 0.57763933]
  [0.276369   0.68273867 0.46312933]
  [0.22251167 0.42849333 0.644842  ]
  [0.33908467 0.72597933 0.724088  ]
  [0.16738    0.61736133 0.61556   ]
  [0.21905067 0.65237067 0.20203067]
  [0.27521033 0.23684067 0.68802267]
  [0.39145633 0.76315933 0.31197733]
  [0.467656   0.247964   0.47071133]
  [0.35919533 0.19221667 0.62940267]
  [0.475083   0.48231267 0.70367133]
  [0.409016   0.21947267 0.23184667]
  [0.35907467 0.40027867 0.17115733]
  [0.41825567 0.44072733 0.44600333]
  [0.257942   0.35055667 0.343158  ]
  [0.470773   0.704064   0.268

100%|██████████| 52/52 [00:00<00:00, 203.12it/s]

4_4
5
[[[0.28416188 0.14208094 0.14208094]
  [0.5        0.5        0.5       ]
  [0.16666667 0.16666667 0.16666667]
  [0.16666667 0.5        0.5       ]
  [0.33333333 0.16666667 0.5       ]
  [0.33333333 0.5        0.16666667]
  [0.16666667 0.5        0.16666667]
  [0.16666667 0.16666667 0.5       ]
  [0.33333333 0.5        0.5       ]
  [0.33333333 0.16666667 0.16666667]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.     